language: python
python:
  - "3.5"
cache: pip

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
before_script: cd bucketbookapp
# command to run tests
script: pytest
