language: python
python:
  - "3.5"
cache: pip

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest
before script: "cd Bucketapp"
# command to run tests
script: python -m unittest discover tests
