language: python
python:
  - "3.5"
cache: pip

# command to install dependencies
install: "pip install -r requirements.txt"
before_script: cd bucketbook\ app/FlaskProject
# command to run tests
script: python test1.py
